# Generated by Django 5.2.17 on 2026-09-26 08:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_course_featured_order_course_is_featured'),
        ('firms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='home_banners/%Y/%m/')),
                ('action_label', models.CharField(blank=True, max_length=60)),
                ('action_url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_banners', to='courses.course')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_banners', to='firms.firm')),
            ],
            options={
                'db_table': 'home_banners',
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['firm', 'is_active'], name='home_banner_firm_id_84f04e_idx'), models.Index(fields=['starts_at', 'ends_at'], name='home_banner_starts__86c03f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('starts_at__isnull', True), ('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='banner_end_after_start')],
            },
        ),
    ]
