# Generated by Django 5.2.17 on 2026-10-01 10:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0006_alter_enrollment_status'),
        ('firms', '0001_initial'),
        ('students', '0002_alter_student_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash')], default='UPI', max_length=30)),
                ('utr_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('payment_screenshot_key', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('student_note', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_payments', to='courses.course')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_payments', to='firms.firm')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_course_payments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_payments', to='students.student')),
            ],
            options={
                'db_table': 'course_payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['firm', 'student', 'course', 'status'], name='course_paym_firm_id_c12039_idx')],
            },
        ),
    ]
