# Generated by Django 5.2.17 on 2026-10-10 08:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0001_initial'),
        ('payments', '0002_enrollmentfeeaccount_installmentpayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('receipt_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('student_name', models.CharField(max_length=255)),
                ('admission_number', models.CharField(blank=True, max_length=100)),
                ('course_name', models.CharField(max_length=255)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=30)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateField()),
                ('file_key', models.CharField(blank=True, max_length=1000)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_voided', models.BooleanField(db_index=True, default=False)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts', to='firms.firm')),
                ('installment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='payments.installmentpayment')),
            ],
            options={
                'db_table': 'installment_payment_receipts',
                'ordering': ['-payment_date', '-generated_at'],
                'indexes': [models.Index(fields=['firm', 'receipt_number'], name='installment_firm_id_f0b21b_idx'), models.Index(fields=['firm', 'is_voided'], name='installment_firm_id_63a635_idx')],
            },
        ),
    ]
