# Generated by Django 5.2.17 on 2026-10-09 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0001_initial'),
        ('materials', '0001_initial'),
        ('progress', '0001_initial'),
        ('students', '0002_alter_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmaterialprogress',
            name='is_verified_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='studentmaterialprogress',
            name='verified_completion_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='studentmaterialprogress',
            name='verified_watched_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StudentVideoWatchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('last_player_position_seconds', models.PositiveIntegerField(default=0)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_watch_sessions', to='firms.firm')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_sessions', to='materials.learningmaterial')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_sessions', to='progress.studentmaterialprogress')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_watch_sessions', to='students.student')),
            ],
            options={
                'db_table': 'student_video_watch_sessions',
                'indexes': [models.Index(fields=['firm', 'student', 'material', 'is_active'], name='student_vid_firm_id_59ee78_idx')],
            },
        ),
    ]
