# Generated by Django 5.2.17 on 2026-09-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
