# Generated by Django 5.2.17 on 2026-09-21 06:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_enrollment_access_end_at_enrollment_access_start_at'),
        ('firms', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scheduled_start_at', models.DateTimeField(db_index=True)),
                ('scheduled_end_at', models.DateTimeField()),
                ('actual_start_at', models.DateTimeField(blank=True, null=True)),
                ('actual_end_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_url', models.URLField(blank=True, max_length=1000)),
                ('meeting_id', models.CharField(blank=True, max_length=255)),
                ('meeting_password', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_classes', to='courses.chapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='live_classes', to='courses.course')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='live_classes', to='firms.firm')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_classes', to='courses.lesson')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='live_classes', to='courses.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='live_classes', to='teachers.teacher')),
            ],
            options={
                'db_table': 'live_classes',
                'ordering': ['scheduled_start_at'],
                'indexes': [models.Index(fields=['firm', 'course', 'status'], name='live_classe_firm_id_fede22_idx'), models.Index(fields=['firm', 'scheduled_start_at'], name='live_classe_firm_id_9e6b2b_idx')],
            },
        ),
    ]
