# Generated by Django 5.2.17 on 2026-09-21 11:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('courses', '0004_course_access_duration_days_course_delivery_mode_and_more'),
        ('firms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('material_type', models.CharField(choices=[('VIDEO', 'Video'), ('PDF', 'PDF'), ('DOCUMENT', 'Document'), ('LINK', 'Link')], db_index=True, max_length=20)),
                ('source', models.CharField(choices=[('LIVE_CLASS_RECORDING', 'Live Class Recording'), ('DIRECT_UPLOAD', 'Direct Upload')], db_index=True, default='DIRECT_UPLOAD', max_length=30)),
                ('file_key', models.CharField(blank=True, max_length=1000)),
                ('external_url', models.URLField(blank=True, max_length=1000)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('available_from', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('available_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('counts_toward_progress', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_materials', to='courses.chapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_materials', to='courses.course')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_materials', to='firms.firm')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_materials', to='courses.lesson')),
                ('live_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='classes.liveclass')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_materials', to='courses.subject')),
            ],
            options={
                'db_table': 'learning_materials',
                'ordering': ['sequence', 'created_at'],
                'indexes': [models.Index(fields=['firm', 'course', 'is_active'], name='learning_ma_firm_id_12eb3b_idx')],
            },
        ),
    ]
