# Generated by Django 5.2.17 on 2026-10-10 09:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0009_course_certificate_required_watch_percentage_and_more'),
        ('firms', '0001_initial'),
        ('students', '0002_alter_student_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCompletionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('certificate_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('verification_code', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('required_watch_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('achieved_watch_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student_name', models.CharField(max_length=255)),
                ('admission_number', models.CharField(blank=True, max_length=100)),
                ('course_name', models.CharField(max_length=255)),
                ('file_key', models.CharField(blank=True, max_length=1000)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_revoked', models.BooleanField(db_index=True, default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completion_certificates', to='courses.course')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='completion_certificate', to='courses.enrollment')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_certificates', to='firms.firm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_certificates', to='students.student')),
            ],
            options={
                'db_table': 'course_completion_certificates',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['firm', 'student', 'course'], name='course_comp_firm_id_451c77_idx'), models.Index(fields=['firm', 'is_revoked'], name='course_comp_firm_id_53c9ff_idx')],
            },
        ),
    ]
