# Generated by Django 5.2.17 on 2026-09-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='access_end_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='access_start_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
