# Generated by Django 5.2.17 on 2026-09-21 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment_access_end_at_enrollment_access_start_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enrollments_firm_id_d6ed55_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enrollments_firm_id_b61c13_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enrollments_firm_id_2c2d3b_idx',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='source',
            field=models.CharField(choices=[('ONLINE_PURCHASE', 'Online Purchase'), ('FIRM_GRANTED', 'Firm Granted')], db_index=True, default='FIRM_GRANTED', max_length=30),
        ),
    ]
