# Generated by Django 5.2.17 on 2026-09-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access_duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='delivery_mode',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('HYBRID', 'Hybrid')], db_index=True, default='ONLINE', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_purchasable_online',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
