# Generated by Django 5.2.17 on 2026-09-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_access_duration_days_course_delivery_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featured_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
