# Generated by Django 5.2.17 on 2026-10-02 11:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_enrollment_status'),
        ('firms', '0001_initial'),
        ('students', '0002_alter_student_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentChapterVideoAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('access_start_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('access_end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_video_accesses', to='courses.chapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_chapter_video_accesses', to='courses.course')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_chapter_video_accesses', to='firms.firm')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_chapter_video_accesses', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapter_video_accesses', to='students.student')),
            ],
            options={
                'db_table': 'student_chapter_video_accesses',
                'indexes': [models.Index(fields=['firm', 'student', 'course', 'is_active'], name='student_cha_firm_id_8fdc06_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'chapter'), name='unique_student_chapter_video_access')],
            },
        ),
    ]
