# Generated by Django 5.2.17 on 2026-10-09 05:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_studentchaptervideoaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_required_watch_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='course',
            name='is_certificate_enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
