# Generated by Django 5.2.17 on 2026-09-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='import_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='import_status',
            field=models.CharField(default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='source_pdf_key',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='assignmentquestion',
            name='answer_text',
            field=models.TextField(blank=True),
        ),
    ]
