# Generated by Django 5.2.17 on 2026-09-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_import_error_assignment_import_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentanswer',
            name='selected_option',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='assignmentquestion',
            name='correct_option',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='assignmentquestion',
            name='option_a',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignmentquestion',
            name='option_b',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignmentquestion',
            name='option_c',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignmentquestion',
            name='option_d',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignmentquestion',
            name='answer_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('FILE', 'File'), ('MCQ', 'MCQ')], default='TEXT', max_length=20),
        ),
    ]
