// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPpbUHnYqkYSww_BPOB2rx3B1gMJb-Y_8',
    appId: '1:833065126862:web:a8e525cc967d73e4bef99f',
    messagingSenderId: '833065126862',
    projectId: 'edusphere-admin-flutter',
    authDomain: 'edusphere-admin-flutter.firebaseapp.com',
    storageBucket: 'edusphere-admin-flutter.firebasestorage.app',
    measurementId: 'G-J7W2E6BZ5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjwsCxoaOjzObarl1Mo2-4ZchAk_lFQj4',
    appId: '1:833065126862:android:e26cca801a61a748bef99f',
    messagingSenderId: '833065126862',
    projectId: 'edusphere-admin-flutter',
    storageBucket: 'edusphere-admin-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0q5_T-a0HFVtZ9qMVvCctcTr5JAt9NWY',
    appId: '1:833065126862:ios:444ec8954802c9b9bef99f',
    messagingSenderId: '833065126862',
    projectId: 'edusphere-admin-flutter',
    storageBucket: 'edusphere-admin-flutter.firebasestorage.app',
    iosBundleId: 'com.example.edusphereAdminFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0q5_T-a0HFVtZ9qMVvCctcTr5JAt9NWY',
    appId: '1:833065126862:ios:444ec8954802c9b9bef99f',
    messagingSenderId: '833065126862',
    projectId: 'edusphere-admin-flutter',
    storageBucket: 'edusphere-admin-flutter.firebasestorage.app',
    iosBundleId: 'com.example.edusphereAdminFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPpbUHnYqkYSww_BPOB2rx3B1gMJb-Y_8',
    appId: '1:833065126862:web:8ea5953834f4be63bef99f',
    messagingSenderId: '833065126862',
    projectId: 'edusphere-admin-flutter',
    authDomain: 'edusphere-admin-flutter.firebaseapp.com',
    storageBucket: 'edusphere-admin-flutter.firebasestorage.app',
    measurementId: 'G-BFLR2Y313F',
  );
}
